### ISSUE TITLE
Doesn't build dist/index.html

### ISSUE THREAD

**Issue by j2l** [jameone/loomse-demo#1]
Happy to see your demo, thanks!
On Windows 10, when I build, I get the dist/ folder but no index.html
only bundle.js and bundle.js.LICENSE.txt files

Here are details:
`
npm run-script build
> loomse-demo@1.0.0 build C:\Users\pm\Downloads\loomse-demo-main
> webpack
asset bundle.js 90.5 KiB [emitted] [minimized] (name: main) 1 related asset
runtime modules 1.25 KiB 6 modules
orphan modules 1.26 KiB [orphan] 2 modules
cacheable modules 566 KiB
  modules by path ./node_modules/ 563 KiB
    ./node_modules/lodash/lodash.js 530 KiB [built] [code generated]
    ./node_modules/loomse/dist/loomse.min.js 8.93 KiB [built] [code generated]
    ./node_modules/redom/dist/redom.es.js 15.9 KiB [built] [code generated]
    ./node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js 6.67 KiB [built] [code generated]
    ./node_modules/css-loader/dist/runtime/api.js 1.57 KiB [built] [code generated]
  modules by path ./src/ 3.32 KiB
    ./src/index.js + 2 modules 2.77 KiB [built] [code generated]
    ./node_modules/css-loader/dist/cjs.js!./src/style.css 566 bytes [built] [code generated]
webpack 5.1.3 compiled successfully in 4201 ms
`

Any idea?

**Comment by james-spears** [comment]
Hello  @j2l,

This was whipped up quite quickly. My apologies it did not work properly for you. I am looking at the repo now and am thinking some files are missing. 

I will look into it now and ping you when I have verified you can build on Windows 10 with the instructions provided.

**Comment by james-spears** [comment]
@j2l,

I believe what happened was I was using an index.html I wrote myself, which was located in the dist folder. Obviously that wont work for people when you specifically .gitignore the dist folder and instruct them to build it themselves. So the changes have been made, the build should produce a dist folder containing an index.html which reprocuces (although not so stylish) the clips on the loomse.org site. 

FYI the output on may Windows 10 machine looks like this: 
```
$ npm run-script build

> loomse-demo@1.0.0 build C:\Users\james\loomse-demo
> webpack

(node:13888) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)
asset bundle.js 607 KiB [emitted] (name: main)
asset index.html 248 bytes [emitted]
runtime modules 1.25 KiB 6 modules
javascript modules 565 KiB
  modules by path ./node_modules/ 563 KiB
    ./node_modules/lodash/lodash.js 530 KiB [built] [code generated]
    ./node_modules/loomse/dist/loomse.min.js 8.93 KiB [built] [code generated]
    ./node_modules/redom/dist/redom.es.js 15.9 KiB [built] [code generated]
    ./node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js 6.67 KiB [built] [code generated]
    ./node_modules/css-loader/dist/runtime/api.js 1.57 KiB [built] [code generated]
  modules by path ./src/ 2.47 KiB
    ./src/index.js 1.57 KiB [built] [code generated]
    ./src/style.css 326 bytes [built] [code generated]
    ./node_modules/css-loader/dist/cjs.js!./src/style.css 594 bytes [built] [code generated]
./src/story-script.json 960 bytes [built] [code generated]
webpack 5.1.3 compiled successfully in 506 ms
```
and I have verified the demo works properly.

Closing this issue, thanks for your feedback.

**Comment by j2l** [comment]
Thank you very much!
I really appreciate your kindness and speed to find the solution
